### ISSUE TITLE
PyQt4 QWebKit not available

### ISSUE THREAD

**Issue by paul70078** [rainerf/ricodebug#53]

**Comment by rainerf** [comment]
Seems that newer Debian/Ubuntu versions removed QtWebKit support from pyqt4: https://wiki.debian.org/Qt4WebKitRemoval. Updating the sources to use pyqt5 (and, ideally, QtWebEngine) should fix this.

**Comment by pagdot** [comment]
Tried porting it to PyQt5 (still QtWebKit), and managed to update quite a few lines, but stopped at this error:
```
Traceback (most recent call last):
  File "ricodebug.py", line 79, in <module>
    main()
  File "ricodebug.py", line 66, in main
    window = MainWindow()
  File "/home/paul/ricodebug/ricodebug/src/views/mainwindow.py", line 58, in __init__
    self.do = DistributedObjects(self)
  File "/home/paul/ricodebug/ricodebug/src/helpers/distributedobjects.py", line 71, in __init__
    self.actions = Actions(self)
  File "/home/paul/ricodebug/ricodebug/src/helpers/actions.py", line 75, in __init__
    self.Run.triggered.connect(do.debugController.run)
TypeError: decorated slot has no signature compatible with triggered(bool)
```
I forked the repo and worked in a branch: [https://github.com/paul70078/ricodebug/tree/qt5_port](https://github.com/paul70078/ricodebug/tree/qt5_port)

I don't have knowledge about PyQt to fix this error
